apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: notes-app-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/FoushWare/request-journey-client-to-server
    targetRevision: main
    path: clusters/dev/apps/notes-app
  destination:
    server: https://kubernetes.default.svc
    namespace: notes-app-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

